app/models.py
# -*- coding: utf-8 -*-
from os import path

from peewee import MySQLDatabase, Model, CharField, BooleanField, IntegerField, DateTimeField, DoubleField
import json
from werkzeug.security import check_password_hash
from flask_login import UserMixin
from app import login_manager
from conf.config import config
import os
import xlrd
from MyQR import myqr

cfg = config[os.getenv('FLASK_CONFIG') or 'default']

db = MySQLDatabase(host=cfg.DB_HOST, user=cfg.DB_USER, passwd=cfg.DB_PASSWD, database=cfg.DB_DATABASE)


class BaseModel(Model):
    class Meta:
        database = db

    def __str__(self):
        r = {}
        for k in self._data.keys():
            try:
                r[k] = str(getattr(self, k))
            except:
                r[k] = json.dumps(getattr(self, k))
        # return str(r)
        return json.dumps(r, ensure_ascii=False)


# 管理员工号
class User(UserMixin, BaseModel):
    username = CharField()  # 用户名
    password = CharField()  # 密码
    fullname = CharField()  # 真实性名
    email = CharField()  # 邮箱
    phone = CharField()  # 电话
    status = BooleanField(default=True)  # 生效失效标识

    def verify_password(self, raw_password):
        return check_password_hash(self.password, raw_password)


# 通知人配置
class QrCode(BaseModel):
    build_company = CharField(default="湖北交投蕲春西高速公路有限公司")  # 建设单位
    design_company = CharField(default="中交公路规划设计院有限公司")  # 设计单位
    check_company = CharField(default="湖北省公路工程咨询监理中心")  # 监理单位
    operation_company = CharField(default="湖北长江路桥股份有限公司")  # 施工单位
    order = IntegerField()  # 排序
    program_location = CharField()  # 工程位置
    # design_code = CharField()  # 设计标识
    pour_time = CharField()  # 浇筑日期
    # standup_time = CharField()  # 抗压日期
    strength = DoubleField()  # 强度
    qr_file_name = CharField(default='')  # 二维码文件的地址


@login_manager.user_loader
def load_user(user_id):
    return User.get(User.id == int(user_id))


# 建表
def create_table():
    db.connect()
    db.create_tables([QrCode, User])


if __name__ == '__main__':
    create_table()
    root_path = path.dirname(path.abspath(__file__))
    root_path1 = root_path[:len(root_path) - 1]
    xld_file = path.join(path.dirname(root_path1), 'conf/qr.xls')
    print(xld_file)
    data = xlrd.open_workbook(xld_file)

    sheet1 = data.sheets()[0]
    nrows = sheet1.nrows
    print('表格总行数', nrows)
    cur_count = 3
    # while cur_count < nrows:
    #     row_values = sheet1.row_values(cur_count)
    #     cur_count += 1
    #     pour_time=xlrd.xldate.xldate_as_datetime(row_values[2], 0).strftime("%Y-%m-%d")
    #     qr = QrCode(order=cur_count, program_location=row_values[1], pour_time=pour_time,strength=float(row_values[3]))
    #     qr.save()

    # 制作二维码
    url = "http://wslio.club/qr/"
    qr_codes = QrCode.select()
    dir = path.join(path.dirname(root_path1), 'app/static/qr')
    for qr_code in qr_codes:
        myqr.run(words='{}{}'.format(url, qr_code.id), save_dir=dir,
                 save_name="{}.jpg".format(qr_code.id))
        qr=QrCode(qr_file_name="qr/{}.jpg".format(qr_code.id))
        qr.id=qr_code.id
        qr.save()

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import FloatField,StringField, SubmitField, BooleanField, PasswordField, SelectField, TextAreaField, HiddenField
from wtforms.validators import DataRequired, Length, Email, Regexp, EqualTo


class QrCodeForm(FlaskForm):
    build_company = StringField('建设单位', validators=[DataRequired(message='不能为空'), Length(0, 64, message='长度不正确')])
    design_company = StringField('设计单位', validators=[DataRequired(message='不能为空'), Length(0, 64, message='长度不正确')])
    check_company = StringField('监理单位', validators=[DataRequired(message='不能为空'), Length(0, 64, message='长度不正确')])
    operation_company = StringField('施工单位', validators=[DataRequired(message='不能为空'), Length(0, 64, message='长度不正确')])
    program_location = StringField('工程位置',
                              validators=[DataRequired(message='不能为空'), Length(0, 64, message='长度不正确')])
    pour_time = StringField('浇筑时间', validators=[DataRequired(message='不能为空'), Length(0, 64, message='长度不正确')])
    strength = FloatField('强度结果', validators=[DataRequired(message='不能为空')])
    submit = SubmitField('提交')

app/__init__.py
from os import path

from flask import Flask
from flask_login import LoginManager
from conf.config import config
import logging
from logging.config import fileConfig
import os

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
log_file_path = path.join(path.dirname(path.abspath(__file__)), 'conf/log-app.conf')
# fileConfig(log_file_path)

def get_logger(name):
    return logging.getLogger(name)


def get_basedir():
    return os.path.abspath(os.path.dirname(__file__))


def get_config():
    return config[os.getenv('FLASK_CONFIG') or 'default']


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    login_manager.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, forms, errors

app/main/views.py
from os import path

from app import get_logger, get_config
import math
from flask import render_template, redirect, url_for, flash, request, send_from_directory, Response
from flask_login import login_required, current_user
from app import utils
from app.models import QrCode
from app.main.forms import QrCodeForm
from . import main

logger = get_logger(__name__)
cfg = get_config()


# 通用列表查询
def common_list(DynamicModel, view):
    # 接收参数
    action = request.args.get('action')
    id = request.args.get('id')
    page = int(request.args.get('page')) if request.args.get('page') else 1
    length = int(request.args.get('length')) if request.args.get('length') else cfg.ITEMS_PER_PAGE

    # 删除操作
    if action == 'del' and id:
        try:
            DynamicModel.get(DynamicModel.id == id).delete_instance()
            flash('删除成功')
        except:
            flash('删除失败')

    # 查询列表
    query = DynamicModel.select()
    total_count = query.count()

    # 处理分页
    if page: query = query.paginate(page, length)

    dict = {'content': utils.query_to_list(query), 'total_count': total_count,
            'total_page': math.ceil(total_count / length), 'page': page, 'length': length}
    return render_template(view, form=dict, current_user=current_user)


# 通用单模型查询&新增&修改
def common_edit(DynamicModel, form, view):
    id = request.args.get('id', '')
    if id:
        # 查询
        model = DynamicModel.get(DynamicModel.id == id)
        if request.method == 'GET':
            utils.model_to_form(model, form)
        # 修改
        if request.method == 'POST':
            if form.validate_on_submit():
                utils.form_to_model(form, model)
                model.save()
                flash('修改成功')
            else:
                utils.flash_errors(form)
    else:
        # 新增
        if form.validate_on_submit():
            model = DynamicModel()
            utils.form_to_model(form, model)
            model.save()
            flash('保存成功')
        else:
            utils.flash_errors(form)
    return render_template(view, form=form, current_user=current_user)


# 通用列表查询
def qr_render(id, DynamicModel, view):
    query = DynamicModel.get(DynamicModel.id == id)

    dict = {'row': utils.obj_to_dict(query)}
    return render_template(view, form=dict)


# 根目录跳转
@main.route('/', methods=['GET'])
@login_required
def root():
    return redirect(url_for('main.index'))


# 首页
@main.route('/index', methods=['GET'])
@login_required
def index():
    return render_template('index.html', current_user=current_user)


# 通知方式查询
@main.route('/notifylist', methods=['GET', 'POST'])
@login_required
def notifylist():
    return common_list(QrCode, 'notifylist.html')


# 通知方式配置
@main.route('/notifyedit', methods=['GET', 'POST'])
@login_required
def notifyedit():
    return common_edit(QrCode, QrCodeForm(), 'notifyedit.html')


# 通知方式配置
@main.route('/qr/<id>', methods=['GET', 'POST'])
def qr_display(id):
    print(id)
    return qr_render(id, QrCode, 'qr.html')

@main.route("/download/<filename>", methods=['GET'])
def download(filename):
    # 此处的filepath是文件的路径，但是文件必须存储在static文件夹下， 比如images\test.jpg
    root_path = path.dirname(path.abspath(__file__))
    root_path1 = root_path[:len(root_path) - 1]
    file = path.join(path.dirname(root_path1), 'static/qr/{}.jpg'.format(filename))

    return send_from_directory('qr', filename, as_attachment=True)

app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    {% block head %}{% endblock %}
    <title>二维码管理平台 | {% block title %}标题{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/font-awesome/css/font-awesome.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/ionicons/css/ionicons.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/bootstrap-slider/slider.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/pace/pace.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/bootstrap-switch/bootstrap-switch.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/select2/select2.min.css') }}">
    {% block css %}{% endblock %}
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/adminlte/css/AdminLTE.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/adminlte/css/skins/skin-blue.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/global.css') }}">
    <!--[if lt IE 9]>
    <script src="plugins/html5shiv.min.js"></script>
    <script src="plugins/respond.min.js"></script>
    <![endif]-->
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
    <!--头部-->
    <header class="main-header">
        <a href="{{ url_for('main.index') }}" class="logo">
            <span class="logo-mini"><b>N</b></span>
            <span class="logo-lg"><b>二维码管理平台</b></span>
        </a>
        <nav class="navbar navbar-static-top">
            <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="{{ url_for('static', filename='images/avatar.jpg') }}" class="user-image"
                                 alt="User Image">
                            <span class="hidden-xs">{{ current_user.username }}</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="user-header">
                                <img src="{{ url_for('static', filename='images/avatar.jpg') }}"
                                     class="img-circle" alt="User Image">
                                <p>
                                    <span>{{ current_user.fullname }}</span>
                                    <small>{{ current_user.email }}</small>
                                </p>
                            </li>
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="{{ url_for('main.index') }}" class="btn btn-default btn-flat">统计信息</a>
                                </div>
                                <div class="pull-right">
                                    <a href="{{ url_for('auth.logout') }}" class="btn btn-default btn-flat">退出登录</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <!--侧边栏-->
    <aside class="main-sidebar">
        <section class="sidebar">
            <ul class="sidebar-menu">
                <li class="header">功能导航</li>
                <li>
                    <a href="{{ url_for('main.index') }}">
                        <i class="fa fa-home"></i>
                        <span>首页</span>
                    </a>
                </li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-user"></i>
                        <span>二维码管理</span>
                        <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="{{ url_for('main.notifyedit') }}"><i class="fa fa-circle-o"></i> 编辑</a></li>
                        <li><a href="{{ url_for('main.notifylist') }}"><i class="fa fa-circle-o"></i> 查询</a></li>
                    </ul>
                </li>
            </ul>
        </section>
    </aside>

    <div class="content-wrapper">
        <!--导航栏-->
        {% block navbar %}{% endblock %}
        <!--正文-->
        <section class="content">
            {% block content %}{% endblock %}

        </section>
    </div>
    <!--页脚-->
    <footer class="main-footer">
        <div class="pull-right hidden-xs">
            <b>版本号</b> 1.0.0
        </div>
        Copyright &copy; 2017 <a href="http://www.si-tech.com.cn">XXXX公司</a>
    </footer>
    <!--模态窗口-->
    <div class="modal-wrapper">
        <div id="alert-modal" class="modal fade">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <!--<button type="button" class="close" data-dismiss="modal" aria-label="Close">-->
                        <!--<span aria-hidden="true">&times;</span></button>-->
                        <h4 class="modal-title">提示</h4>
                    </div>
                    <div class="modal-body">
                        提示内容
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default pull-left btn-no" data-dismiss="modal">取消</button>
                        <button type="button" class="btn btn-default btn-yes" data-dismiss="modal">确定</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{{ url_for('static', filename='plugins/jQuery/jquery-2.2.3.min.js') }}"></script>
<script src="{{ url_for('static', filename='plugins/bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='plugins/slimScroll/jquery.slimscroll.min.js') }}"></script>
<script src="{{ url_for('static', filename='plugins/fastclick/fastclick.js') }}"></script>
<script src="{{ url_for('static', filename='plugins/bootstrap-slider/bootstrap-slider.js') }}"></script>
<script src="{{ url_for('static', filename='plugins/pace/pace.min.js') }}"></script>
<script src="{{ url_for('static', filename='plugins/bootstrap-switch/bootstrap-switch.min.js') }}"></script>
<script src="{{ url_for('static', filename='plugins/select2/select2.full.min.js') }}"></script>
<script src="{{ url_for('static', filename='plugins/adminlte/js/app.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/global.js') }}"></script>
{% block scripts %}{% endblock %}
</body>
</html>

app/templates/index.html
{% extends "base.html" %}

{% block title %}首页{% endblock %}

{% block navbar %}
<section class="content-header">
    <h1>首页</h1>
    <ol class="breadcrumb">
        <li><i class="fa fa-dashboard"></i> 当前位置</li>
        <li class="active">首页</li>
    </ol>
</section>
{% endblock %}

{% block content %}
<div class="box box-primary">
    <div class="box-body">
        <div class="row">
            <div class="col-lg-3 col-xs-6">
                <div class="small-box bg-aqua">
                    <div class="inner">
                        <h3 id="count01">0</h3>
                        <p>统计信息</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-ios-gear-outline"></i>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-xs-6">
                <div class="small-box bg-green">
                    <div class="inner">
                        <h3 id="count02">0</h3>
                        <p>统计信息</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-iphone"></i>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-xs-6">
                <div class="small-box bg-yellow">
                    <div class="inner">
                        <h3 id="count03">0</h3>
                        <p>统计信息</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-person-add"></i>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-xs-6">
                <div class="small-box bg-red">
                    <div class="inner">
                        <h3 id="count04">0</h3>
                        <p>统计信息</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-pie-graph"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="box-footer">
        <div class="alert alert-info alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <h4><i class="icon fa fa-info"></i> 温馨提示</h4>
            <ol>
                <li>温馨提示温馨提示温馨提示</li>
                <li>温馨提示温馨提示温馨提示</li>
            </ol>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    function initPage() {
        var jsInObj = null;
        restTemplate("GET", "/stats/summary", jsInObj, function (jsOutObj) {
            $("#count01").text(jsOutObj.batch_count);
            $("#count02").text(jsOutObj.test_count);
            $("#count03").text(jsOutObj.succ_count);
            $("#count04").text(jsOutObj.fail_count);
        });
    }
</script>
{% endblock %}

app/templates/message.html
{% if get_flashed_messages() %}
<div class="alert callout callout-info" id="alertarea">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <h4><i class="icon fa fa-info"></i>提示信息</h4>
    {% for message in get_flashed_messages() %}
    <p>{{ message }}</p>
    {% endfor %}
</div>
{% endif %}

app/templates/notifyedit.html
{% extends "base.html" %}

{% block title %}通知方式配置{% endblock %}


{% block navbar %}
<section class="content-header">
    <h1>工程数据</h1>
    <ol class="breadcrumb">
        <li><i class="fa fa-dashboard"></i> 当前位置</li>
        <li class="active">工程数据</li>
        <li class="active">工程数据配置</li>
    </ol>
</section>
{% endblock %}


{% block content %}
<div class="box box-primary">
    <form method="post">
        {{form.hidden_tag()}}
        <div class="box-header with-border">
            {% include 'message.html' %}
        </div>

        <div class="box-body">
            <div class="col-md-6">
                <div class="form-group">
                    <label>{{form.build_company.label}}</label>
                    {{form.build_company(class_="form-control",placeholder="请输入 列表顺序")}}
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label>{{form.design_company.label}}</label>
                    {{form.design_company(class_="form-control",placeholder="请输入")}}
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label>{{form.check_company.label}}</label>
                    {{form.check_company(class_="form-control",placeholder="请输入")}}
                </div>
            </div>
             <div class="col-md-6">
                <div class="form-group">
                    <label>{{form.operation_company.label}}</label>
                    {{form.operation_company(class_="form-control",placeholder="请输入")}}
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label>{{form.program_location.label}}</label>
                    {{form.program_location(class_="form-control",placeholder="请输入")}}
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label>{{form.pour_time.label}}</label>
                    {{form.pour_time(class_="form-control",placeholder="请输入")}}
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label>{{form.strength.label}}</label>
                    {{form.strength(class_="form-control",placeholder="请输入")}}
                </div>
            </div>
        </div>

        <div class="box-footer">
            <div class="col-md-12">
                {{form.submit(class_="btn btn-primary pull-right")}}
            </div>
        </div>
    </form>
</div>
{% endblock %}

{% block scripts %}
<script>
    function initPage() {
        slide_value = $(".slider").val() == "" ? 50 : parseInt($(".slider").val());
        $(".slider").slider({
            id: "blue",
            max: 100,
            value: slide_value
        });

        switch_value = $('#status')[0].checked
        $('#status').bootstrapSwitch({
            state: switch_value,
            onText: '生效',
            offText: '失效'

        });

        $(".select2").select2();
    }
</script>
{% endblock %}

app/templates/notifylist.html
{% extends "base.html" %}

{% block title %}工程管理查询{% endblock %}
{% block navbar %}
<section class="content-header">
    <h1>工程管理查询</h1>
    <ol class="breadcrumb">
        <li><i class="fa fa-dashboard"></i> 当前位置</li>
        <li class="active">工程管理</li>
        <li class="active">工程管理查询</li>
    </ol>
</section>
{% endblock %}

{% block content %}
<div class="box box-primary">
    <div class="box-header with-border">
        {% include 'message.html' %}
    </div>

    <div class="box-body">
        {% if form%}
        <table class="table table-bordered">
            <tr>
                <th>ID</th>
                <th>建设单位</th>
                <th>设计单位</th>
                <th>监理单位</th>
                <th>施工单位</th>
                <th>工程部位</th>
                <th>浇筑日期</th>
                <th>强度结果</th>
                <th>二维码预览</th>
                <th>编辑</th>
                <th>删除</th>
            </tr>
            {% for row in form.content %}
            <tr>
                <td>{{row.id}}</td>
                <td>{{row.build_company}}</td>
                <td>{{row.design_company}}</td>
                <td>{{row.check_company}}</td>
                <td>{{row.operation_company}}</td>
                <td>{{row.program_location}}</td>
                <td>{{row.pour_time}}</td>
                <td>{{row.strength}}</td>
                <td><a href="{{ url_for('static', filename=row.qr_file_name) }} ">下载</a></td>
                <td><a class='fa fa-lg fa-edit text-light-blue'
                       href='{{ url_for("main.notifyedit", id=row.id) }}'></a></td>
                <td><a class='fa fa-lg fa-warning text-red' href='?action=del&id={{row.id}}'></a></td>
            </tr>
            {% endfor %}
        </table>
        {% endif %}
    </div>

    <div class="box-footer clearfix">
        {% if form%}
        <ul class="pagination pagination-sm no-margin pull-right">
            <li><a href="#">&laquo;</a></li>
            {% for i in range(1, form.total_page+ 1) %}
            {% if i == form.page %}
            <li><a href="?page={{i}}"><b>{{i}}</b></a></li>
            {% else %}
            <li><a href="?page={{i}}">{{i}}</a></li>
            {% endif %}
            {% endfor %}
            <li><a href="#">&raquo;</a></li>
        </ul>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    function initPage() {
        slide_value = $(".slider").val() == "" ? 50 : parseInt($(".slider").val());
        $(".slider").slider({
            id: "blue",
            max: 100,
            value: slide_value
        });

        $('.status').bootstrapSwitch();
        $(".status").on("switchChange.bootstrapSwitch", function (event, state) {
            switchStatus($(this).data("id"), state, this);
        });
    }
    function switchStatus(id, status, switchBox) {
        restTemplate("PUT", "/notifies/" + id + "/status/" + status, null, function () {
            $($(switchBox)).bootstrapSwitch("state", status);
        });
    }
</script>
{% endblock %}